version: "3.7"

services:

    db: 
        container_name: db_avaliacao_compras
        image: postgres
        restart: always
        environment: 
            - POSTGRES_DB=db_avaliacao_compras
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
        ports: 
            - "5432:5432"
        volumes: 
            - ./pgdata:/var/lib/postgresql/data

    app:
        container_name: app_avaliacao_compras
        build: .
        command: yarn dev
        volumes:
            - .:/usr/src/app
        depends_on:
            - db
        ports: 
            - "3333:3333"